# Changes here will be overwritten by Copier
_commit: d56cb12
_src_path: https://github.com/python-project-templates/base.git
add_extension: rust
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A Rust-Python project template
project_name: python template rust
python_version_primary: '3.9'
team: Python Project Template Authors
