name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v5

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - uses: actions-ext/rust/setup@main

    - name: Install dependencies
      run: make develop

    - name: Lint
      run: make lint

    - name: Checks
      run: make checks
      if: matrix.os == 'ubuntu-latest'

    - name: Build
      run: make build

    - name: Test
      run: make coverage

    - name: Upload test results (Python)
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: '**/junit.xml'
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/junit.xml'
      if: matrix.os == 'ubuntu-latest'

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
      if: runner.os == 'Linux' && runner.arch == 'X64'

    - name: Make dist
      run: |
        make dist-rs
        make dist-py-sdist
        make dist-py-wheel
        make dist-check
      if: matrix.os == 'ubuntu-latest'

    - name: Make dist
      run: |
        make dist-py-wheel
        make dist-check
      env:
        CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=11.0
      if: matrix.os != 'ubuntu-latest'

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{matrix.os}}
        path: dist
